/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootLayoutImport } from './routes/_rootLayout'
import { Route as RootLayoutIndexImport } from './routes/_rootLayout.index'
import { Route as RootLayoutCategoryIdImport } from './routes/_rootLayout.category.$id'

// Create/Update Routes

const RootLayoutRoute = RootLayoutImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutIndexRoute = RootLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutCategoryIdRoute = RootLayoutCategoryIdImport.update({
  path: '/category/$id',
  getParentRoute: () => RootLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_rootLayout/': {
      id: '/_rootLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexImport
      parentRoute: typeof RootLayoutImport
    }
    '/_rootLayout/category/$id': {
      id: '/_rootLayout/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof RootLayoutCategoryIdImport
      parentRoute: typeof RootLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  RootLayoutRoute: RootLayoutRoute.addChildren({
    RootLayoutIndexRoute,
    RootLayoutCategoryIdRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_rootLayout"
      ]
    },
    "/_rootLayout": {
      "filePath": "_rootLayout.tsx",
      "children": [
        "/_rootLayout/",
        "/_rootLayout/category/$id"
      ]
    },
    "/_rootLayout/": {
      "filePath": "_rootLayout.index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/category/$id": {
      "filePath": "_rootLayout.category.$id.tsx",
      "parent": "/_rootLayout"
    }
  }
}
ROUTE_MANIFEST_END */
